language: python
dist: trusty

git:
  depth: 10

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  chrome: stable

cache:
  pip: true

before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - ./travis_install.sh

branches:
  only:
    - master

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"

script:
  - ./travis_run.sh

env:
  global:
    - DJANGO_SETTINGS_MODULE=cfgov.settings.test
    - DJANGO_STAGING_HOSTNAME=content.localhost
    - COVERALLS_PARALLEL=true
    - PGPORT=5433
    - TEST_DATABASE_URL=postgres://travis:travis@localhost:5433/travis

jobs:
  fast_finish: true
  include:
    - stage: Run Tests
      env: RUNTEST=frontend
      if: type = pull_request
      python: 2.7
    - env:
        - RUNTEST=backend
        - TEST_RUNNER=cfgov.test.StdoutCapturingTestRunner
      if: type = pull_request
      python: 2.7
    - env:
        - RUNTEST=backend3
        - TEST_RUNNER=cfgov.test.StdoutCapturingTestRunner
      if: type = pull_request
      python: 3.6
    - stage: Docs Deploy
      if: type != pull_request
      env: RUNTEST=docs
      deploy:
        provider: pages
        local_dir: site
        skip-cleanup: true
        github_token: $GITHUB_TOKEN
